monolog:
    handlers:
        # exception log handler
        exception:
            type: stream
            path: '%kernel.logs_dir%/exception.log'
            level: error
            channels: ['!event']

        # exclude specific http codes from the exception log
        filtered:
            type: fingers_crossed
            action_level: error
            handler: exception
            excluded_http_codes: [403, 404, 429, 501, 503]

when@dev:
    monolog:
        handlers:
            # debug dev log handler
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
